# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: python/momotalk.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15python/momotalk.proto\x12\x08tutorial\"\x88\x03\n\x0cMomotalkItem\x12\x16\n\x0eMessageGroupId\x18\x01 \x01(\r\x12\n\n\x02Id\x18\x02 \x01(\r\x12\x13\n\x0b\x43haracterId\x18\x03 \x01(\r\x12\x34\n\x10MessageCondition\x18\x04 \x01(\x0e\x32\x1a.tutorial.MessageCondition\x12\x16\n\x0e\x43onditionValue\x18\x05 \x01(\r\x12\x1b\n\x13PreConditionGroupId\x18\x06 \x01(\r\x12#\n\x1bPreConditionFavorScheduleId\x18\x07 \x01(\r\x12\x17\n\x0f\x46\x61vorScheduleId\x18\x08 \x01(\r\x12\x13\n\x0bNextGroupId\x18\t \x01(\r\x12\x1c\n\x14\x46\x65\x65\x64\x62\x61\x63kTimeMillisec\x18\n \x01(\r\x12*\n\x0bMessageType\x18\x0b \x01(\x0e\x32\x15.tutorial.MessageType\x12\x11\n\tImagePath\x18\x0c \x01(\t\x12\x11\n\tMessageKR\x18\r \x01(\t\x12\x11\n\tMessageJP\x18\x0e \x01(\t\"8\n\x0cMomotalkData\x12(\n\x08\x44\x61taList\x18\x01 \x03(\x0b\x32\x16.tutorial.MomotalkItem*H\n\x10MessageCondition\x12\t\n\x05NoneB\x10\x00\x12\x0f\n\x0b\x46\x61vorRankUp\x10\x01\x12\n\n\x06\x41nswer\x10\x02\x12\x0c\n\x08\x46\x65\x65\x64\x62\x61\x63k\x10\x03*-\n\x0bMessageType\x12\t\n\x05NoneA\x10\x00\x12\x08\n\x04Text\x10\x01\x12\t\n\x05Image\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'python.momotalk_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGECONDITION._serialized_start=488
  _MESSAGECONDITION._serialized_end=560
  _MESSAGETYPE._serialized_start=562
  _MESSAGETYPE._serialized_end=607
  _MOMOTALKITEM._serialized_start=36
  _MOMOTALKITEM._serialized_end=428
  _MOMOTALKDATA._serialized_start=430
  _MOMOTALKDATA._serialized_end=486
# @@protoc_insertion_point(module_scope)
