/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AssetPreviewer: typeof import('./src/components/ResourceExplorer/AssetPreviewer.vue')['default']
    CodeMirror: typeof import('./src/components/CodeMirror/CodeMirror.vue')['default']
    ConversationCard: typeof import('./src/components/VisualEditor/ConversationCard.vue')['default']
    EditorLayout: typeof import('./src/components/EditorLayout/index.vue')['default']
    FileItem: typeof import('./src/components/ResourceExplorer/FileItem.vue')['default']
    JSONEditor: typeof import('./src/components/JSONEditor/JSONEditor.vue')['default']
    NexonScriptEditor: typeof import('./src/components/NexonScriptEditor/NexonScriptEditor.vue')['default']
    NexonScriptEditorToolbar: typeof import('./src/components/NexonScriptEditor/NexonScriptEditorToolbar.vue')['default']
    ResourceExplorer: typeof import('./src/components/ResourceExplorer/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    VisualEditor: typeof import('./src/components/VisualEditor/VisualEditor.vue')['default']
    VisualEditorCard: typeof import('./src/components/VisualEditor/VisualEditorCard.vue')['default']
  }
}
