/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    NButton: typeof import('naive-ui')['NButton'];
    NDropdown: typeof import('naive-ui')['NDropdown'];
    NInputGroup: typeof import('naive-ui')['NInputGroup'];
    NSpace: typeof import('naive-ui')['NSpace'];
    NSwitch: typeof import('naive-ui')['NSwitch'];
    NTag: typeof import('naive-ui')['NTag'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
  }
}
