CharacterId: 10074
translator: ""
title:
  - TextJp: 今日は安全日です
    TextCn: ""
    TextKr: 오늘은 위험하지 않습니다
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1007402
    FavorScheduleId: 100742
    CharacterId: 10074
  - TextJp: ありのままの姿
    TextCn: ""
    TextKr: 보는 사람이 없다면 의미도 없다
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1007403
    FavorScheduleId: 100743
    CharacterId: 10074
  - TextJp: 不器用な一面
    TextCn: ""
    TextKr: 의외로 서툰 모습
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1007405
    FavorScheduleId: 100745
    CharacterId: 10074
content:
  - MessageKR: 선생님
    MessageJP: こんにちは、先生
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740010
    Id: 100740010
    CharacterId: 10074
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 혹시 지금 좀……. 괜찮으신가요?
    MessageJP: いま、少しお時間よろしいでしょうか？
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740020
    Id: 100740020
    CharacterId: 10074
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740030
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 괜찮은데, 무슨 일이야?
    MessageJP: 大丈夫だよ、ハナコ
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740030
    Id: 100740030
    CharacterId: 10074
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740040
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 음? 하나코?
    MessageJP: どうかしたの？
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740030
    Id: 100740040
    CharacterId: 10074
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740040
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 별 건 아니고……. 그저…….
    MessageJP: 大したことではないのですが
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740040
    Id: 100740050
    CharacterId: 10074
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740050
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 좋은 것들
    MessageJP: その……
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740040
    Id: 100740060
    CharacterId: 10074
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740050
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 이 좀 생겨서 말이에요.
    MessageJP: イイコトがあったものでして♡
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740050
    Id: 100740070
    CharacterId: 10074
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740060
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: ……좋은 것?
    MessageJP: イイコト？
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740060
    Id: 100740080
    CharacterId: 10074
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740070
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 하나코가 말하니 의미심장하네.
    MessageJP: ハナコが言うと、なんだか意味深に聞こえるね……
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740060
    Id: 100740090
    CharacterId: 10074
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740070
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 후후
    MessageJP: ふふっ
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740070
    Id: 100740100
    CharacterId: 10074
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740080
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 꼭
    MessageJP: その……
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740080
    Id: 100740110
    CharacterId: 10074
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740090
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 함께 봐주셨으면 해요.
    MessageJP: ぜひ先生に見ていただきたく
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740080
    Id: 100740120
    CharacterId: 10074
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100742
    NextGroupId: 100740090
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생님
    MessageJP: 先生、どうされました？
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740090
    Id: 100740130
    CharacterId: 10074
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 100740080
    PreConditionFavorScheduleId: 100742
    FavorScheduleId: 0
    NextGroupId: 100740100
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 이야기가 다르잖아!
    MessageJP: 話が違うんだけど！？
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740100
    Id: 100740140
    CharacterId: 10074
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740110
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 이번엔 진짜 괜찮다고 했잖아요!
    MessageJP: ここでは安心してって言ってなかった！？
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740100
    Id: 100740150
    CharacterId: 10074
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740110
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 어머
    MessageJP: あら
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740110
    Id: 100740160
    CharacterId: 10074
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740120
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 괜찮다고 말씀드린 건 맞는 걸요
    MessageJP: たしかに、そう言いましたが……
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740110
    Id: 100740170
    CharacterId: 10074
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740120
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: "'둘이 있을 때'라고 말씀드렸잖아요?"
    MessageJP: それは2人きりの時だけですよ？
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740120
    Id: 100740180
    CharacterId: 10074
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740130
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 후후
    MessageJP: うふふっ
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740120
    Id: 100740190
    CharacterId: 10074
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740130
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: ♡
    MessageJP: ♡
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740130
    Id: 100740200
    CharacterId: 10074
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740140
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 여긴 정말 물이 시원하네요
    MessageJP: ここの水は、本当に気持ちが良いですね
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740140
    Id: 100740210
    CharacterId: 10074
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 100740130
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740150
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 깨끗하기도 하고
    MessageJP: こんなにも透き通っているなんて……
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740150
    Id: 100740220
    CharacterId: 10074
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740160
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 수영 중이야?
    MessageJP: もしかして海にいるの？
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740160
    Id: 100740230
    CharacterId: 10074
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740170
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아뇨
    MessageJP: いえ
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740170
    Id: 100740240
    CharacterId: 10074
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740180
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 바다도 좋지만, 저는 이쪽이 좀 더 취향이라서요.
    MessageJP: 海も好きなのですが、今は別のところに
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740170
    Id: 100740250
    CharacterId: 10074
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740180
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생님께도 보여드리고 싶은 곳이에요.
    MessageJP: 機会があれば、先生も見てみませんか？
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740180
    Id: 100740260
    CharacterId: 10074
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100743
    NextGroupId: 100740190
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생님?
    MessageJP: 先生に置いていかれてしまって、残念です
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740190
    Id: 100740270
    CharacterId: 10074
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 100740180
    PreConditionFavorScheduleId: 100743
    FavorScheduleId: 0
    NextGroupId: 100740200
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 빨리 가셨네요. 이왕이면 같이 말린 뒤에 함께 돌아가고 싶었는데.
    MessageJP: 服が乾くまで待ってから、一緒に帰りたかったのですが……
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740200
    Id: 100740280
    CharacterId: 10074
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740210
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그건 아무래도 역시 좀…….
    MessageJP: それは流石に……
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740210
    Id: 100740290
    CharacterId: 10074
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740220
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 방심한 사이 당해버렸어…….
    MessageJP: ちょっと油断してたよ……
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740210
    Id: 100740300
    CharacterId: 10074
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740220
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 후후
    MessageJP: うふふっ、冗談です
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740220
    Id: 100740310
    CharacterId: 10074
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740230
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 덕분에 재밌었어요. 선생님.
    MessageJP: とっても楽しい時間でした。ありがとうございます、先生
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740230
    Id: 100740320
    CharacterId: 10074
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740240
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생님?
    MessageJP: 先生
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740240
    Id: 100740330
    CharacterId: 10074
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 100740230
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740250
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 지금 어디 계신가요?
    MessageJP: 今どちらにいらっしゃいますか？
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740250
    Id: 100740340
    CharacterId: 10074
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740260
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 괜찮으시다면 이번에는, 제가 찾아 뵈려고 하는데…….
    MessageJP: その、お話ししたいことが……
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740250
    Id: 100740350
    CharacterId: 10074
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740260
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 응? 무슨 일이야?
    MessageJP: どうしたの？
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740260
    Id: 100740360
    CharacterId: 10074
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740270
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 하나코가 직접 온다고?
    MessageJP: 何か相談事？
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740260
    Id: 100740370
    CharacterId: 10074
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740270
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 네
    MessageJP: はい
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740270
    Id: 100740380
    CharacterId: 10074
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740280
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 장소만 알려주시면…….
    MessageJP: 場所を教えていただけたら
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740270
    Id: 100740390
    CharacterId: 10074
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100740280
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 지금 바로 갈게요 ♡
    MessageJP: すぐそちらに向かいます♡
    MessageCN: ""
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100740280
    Id: 100740400
    CharacterId: 10074
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100745
    NextGroupId: 0
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
