CharacterId: 20029
translator: ARUKU
title:
  - TextJp: 夏の海の大和撫子
    TextCn: 夏日海滩的大和抚子
    TextKr: 여름 바다의 요조숙녀
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 2002902
    FavorScheduleId: 200292
    CharacterId: 20029
    unsure: false
  - TextJp: 夏の海の読心術
    TextCn: 夏日海滩的读心术
    TextKr: 여름 바다의 독심술
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 2002903
    FavorScheduleId: 200293
    CharacterId: 20029
    unsure: false
  - TextJp: 夏の海の思い出
    TextCn: 夏日海滩的回忆
    TextKr: 여름 바다의 추억
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 2002905
    FavorScheduleId: 200295
    CharacterId: 20029
    unsure: false
content:
  - MessageKR: 선생님?
    MessageJP: 先生、
    MessageCN: 老师，
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290010
    Id: 200290010
    CharacterId: 20029
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200290020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 오늘 해변가로 나갈 준비, 다 되셨죠?
    MessageJP: 海に出かける準備はお済みですか？
    MessageCN: 您做好前往海边的准备了吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290020
    Id: 200290020
    CharacterId: 20029
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200290030
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 음…… 그런데 난 뭘 준비해야 할지……
    MessageJP: えっと、私は何を持っていけば……
    MessageCN: 那个，我要带什么东西去……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290030
    Id: 200290030
    CharacterId: 20029
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200290040
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 후훗. 괜찮답니다.
    MessageJP: ふふっ、大丈夫です
    MessageCN: 呵呵，毋需担心
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290040
    Id: 200290040
    CharacterId: 20029
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200290050
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 웬만한 것은 제가 준비해 둘 테니, 선생님께서는 몸만 오시면 돼요.
    MessageJP: 持ち物は私が用意しましたので、先生は心の準備をしていらしてください
    MessageCN: 我会准备好行李的，老师就请带上来海边放松的心情吧
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290040
    Id: 200290050
    CharacterId: 20029
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200290050
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 아, 그래도…… 수영복은 직접 준비해 주세요?
    MessageJP: あ……それと、自分の水着もお持ちくださいね
    MessageCN: 啊……还有，请务必带上自己的泳装哦
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290040
    Id: 200290060
    CharacterId: 20029
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200290050
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 그건 당연한 거잖아……
    MessageJP: さ、流石にそれくらいは……
    MessageCN: 再、再怎么说我也不至于……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290050
    Id: 200290070
    CharacterId: 20029
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200290060
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 네. 그러면 제 방문 앞에서 뵈어요.
    MessageJP: ふふっ。では、私の部屋の前でお会いしましょう
    MessageCN: 呵呵。那么，就请来我的房间门口吧
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290060
    Id: 200290080
    CharacterId: 20029
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200290070
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 기다리고 있겠습니다.
    MessageJP: お待ちしております
    MessageCN: 我等着您
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290070
    Id: 200290090
    CharacterId: 20029
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200292
    NextGroupId: 200290080
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 일광욕은 마음에 드셨나요, 선생님?
    MessageJP: 日光浴はいかがでしたか、先生？
    MessageCN: 日光浴感觉如何，老师？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290080
    Id: 200290100
    CharacterId: 20029
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 200290070
    PreConditionFavorScheduleId: 200292
    FavorScheduleId: 0
    NextGroupId: 200290090
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 너무 마음에 들어서 문제였던 것 같아……
    MessageJP: 生きてて良かった……
    MessageCN: 活着真是太好了……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290090
    Id: 200290110
    CharacterId: 20029
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200290100
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 네? 그건 무슨 말씀이신지……?
    MessageJP: はい……？えっと、体調は大丈夫でしょうか？
    MessageCN: 诶……？那个，身体不要紧吧？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290100
    Id: 200290120
    CharacterId: 20029
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200290110
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 저…… 어쨌든 어딘가 아프다거나 하신 건 아니죠?
    MessageJP: お水、忘れずに飲んでから寝てくださいね
    MessageCN: 睡前不要忘记喝水哦
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290100
    Id: 200290130
    CharacterId: 20029
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200290110
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: "미모리 덕분에 완전 괜찮아! "
    MessageJP: ミモリのおかげで、もう元気だよ！
    MessageCN: 多亏了三森，我现在很精神哦！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290110
    Id: 200290140
    CharacterId: 20029
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200290120
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 네? 후훗. 그렇다면 다행이네요.
    MessageJP: ふふっ、それなら良かったです
    MessageCN: 呵呵，那就好
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290120
    Id: 200290150
    CharacterId: 20029
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200290130
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 그럼, 또 나중에.
    MessageJP: では、また後でお会いしましょう
    MessageCN: 那么，之后再见吧
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290130
    Id: 200290160
    CharacterId: 20029
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200290140
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: "안녕하세요. 선생님. "
    MessageJP: おはようございます、先生
    MessageCN: 老师，早上好
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290140
    Id: 200290170
    CharacterId: 20029
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 200290130
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200290150
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 좋은 아침이네. 미모리.
    MessageJP: おはよう、ミモリ
    MessageCN: 早上好，三森
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290150
    Id: 200290180
    CharacterId: 20029
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200290160
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 오늘도 날씨가 좋구나~
    MessageJP: 今日も良い天気だね
    MessageCN: 今天也是个好天气呢
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290150
    Id: 200290190
    CharacterId: 20029
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200290160
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: "앗, 네. 그러게요. "
    MessageJP: はい、本当に良いお天気ですね
    MessageCN: 嗯，今天天气真的很好呢
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290160
    Id: 200290200
    CharacterId: 20029
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200290170
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 바람도 솔솔 불어오는 게 무척이나 기분이 좋아서.
    MessageJP: 穏やかな風もあって、過ごしやすいですし
    MessageCN: 而且还吹着微风，很宜居呢
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290160
    Id: 200290210
    CharacterId: 20029
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200290170
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 왠지 좋은 일이 일어날 것 같은 날이네요.
    MessageJP: なんだか素敵な日になりそうです
    MessageCN: 总觉得，今天会是个美好的日子
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290170
    Id: 200290220
    CharacterId: 20029
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200290180
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 그럼 오늘도 파이팅이에요!
    MessageJP: それでは、今日も頑張りましょう！
    MessageCN: 那么，今天也一起加油吧！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290170
    Id: 200290230
    CharacterId: 20029
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200293
    NextGroupId: 200290180
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: "안녕하세요. 선생님. "
    MessageJP: 先生
    MessageCN: 老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290180
    Id: 200290240
    CharacterId: 20029
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 200290170
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200290190
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 오늘은 선생님과 해변에서 함께 시간을 보내고 싶은데
    MessageJP: 今日は先生と一緒に、海辺で過ごしたいのですが……
    MessageCN: 今天，我想和老师一起在海边度过……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290190
    Id: 200290250
    CharacterId: 20029
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200290200
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 괜찮으신가요?
    MessageJP: お時間、大丈夫でしょうか？
    MessageCN: 您有时间吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290200
    Id: 200290260
    CharacterId: 20029
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200290210
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 얼마든지 좋아.
    MessageJP: もちろんだよ
    MessageCN: 当然了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290210
    Id: 200290270
    CharacterId: 20029
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200290220
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: "그러면 잘 부탁드립니다.  "
    MessageJP: それでは、よろしくお願いします
    MessageCN: 那么，请多关照
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290220
    Id: 200290280
    CharacterId: 20029
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200290230
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 뭔가…… 엄청나게 기대가 되네요.
    MessageJP: ……とても、楽しみです
    MessageCN: ……我，非常期待
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290230
    Id: 200290290
    CharacterId: 20029
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200290240
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 저, 지금 가슴이 막 뛰고 그러는 거 있죠?
    MessageJP: こんなにも、胸がドキドキするなんて……
    MessageCN: 没想到，心跳竟会如此地……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290240
    Id: 200290300
    CharacterId: 20029
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200290250
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 음, 저기. 살살 부탁합니다……?
    MessageJP: も、もう少し気楽にね……？
    MessageCN: 稍、稍微放轻松一点吧……？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200290250
    Id: 200290310
    CharacterId: 20029
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200295
    NextGroupId: 0
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
