CharacterId: 20027
translator: 罐子
title:
  - TextJp: シュノーケリング
    TextCn: 浮潜
    TextKr: 스노클링
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 2002702
    FavorScheduleId: 200272
    CharacterId: 20027
  - TextJp: ペース配分
    TextCn: 步调分配
    TextKr: 페이스 조절
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 2002703
    FavorScheduleId: 200273
    CharacterId: 20027
  - TextJp: 期待
    TextCn: 期待
    TextKr: 기대감
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 2002705
    FavorScheduleId: 200275
    CharacterId: 20027
content:
  - MessageKR: 선생님
    MessageJP: 先生
    MessageCN: 老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270010
    Id: 200270010
    CharacterId: 20027
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200270020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 괜찮다면
    MessageJP: もし、大丈夫なら
    MessageCN: 如果，方便的话
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270020
    Id: 200270020
    CharacterId: 20027
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200270030
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 혹시 지금 좀 와 줄 수 있어?
    MessageJP: 今から来れる？
    MessageCN: 现在能来我这里吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270020
    Id: 200270030
    CharacterId: 20027
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200270030
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 응. 무슨 일이야?
    MessageJP: うん、大丈夫だよ
    MessageCN: 嗯，可以哦
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270030
    Id: 200270040
    CharacterId: 20027
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200270040
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 괜찮지. 지금 어딘데?
    MessageJP: どこにいるの？
    MessageCN: 白子在哪里？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270030
    Id: 200270050
    CharacterId: 20027
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200270040
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 음
    MessageJP: ん
    MessageCN: 嗯
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270040
    Id: 200270060
    CharacterId: 20027
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200270050
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그게…….
    MessageJP: えっと……
    MessageCN: 那个……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270050
    Id: 200270070
    CharacterId: 20027
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200272
    NextGroupId: 200270060
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 생각했던 것만큼, 대단한 재료는 아니었어.
    MessageJP: 幻なんて言うくらいだし、もっと美味しいと思ってた
    MessageCN: 都到被称为梦幻的程度了，我还以为会更好吃一点的
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270060
    Id: 200270080
    CharacterId: 20027
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 200270050
    PreConditionFavorScheduleId: 200272
    FavorScheduleId: 0
    NextGroupId: 200270070
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 좀 아쉽네
    MessageJP: ちょっと残念
    MessageCN: 有点遗憾
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270070
    Id: 200270090
    CharacterId: 20027
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200270080
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그래도 과정은 즐거웠잖아?
    MessageJP: でも、楽しかったね
    MessageCN: 但是，很开心呢
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270080
    Id: 200270100
    CharacterId: 20027
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200270090
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그래도 시로코가 만들어 준 거라 좋았어.
    MessageJP: シロコと一緒に過ごせて、すごく嬉しかったよ
    MessageCN: 我很高兴能和白子一起去找海味哦
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270080
    Id: 200270110
    CharacterId: 20027
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200270090
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생님…….
    MessageJP: 先生……
    MessageCN: 老师……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270090
    Id: 200270120
    CharacterId: 20027
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200270100
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: …….
    MessageJP: ……
    MessageCN: ……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270100
    Id: 200270130
    CharacterId: 20027
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200270110
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 응
    MessageJP: うん
    MessageCN: 嗯
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270110
    Id: 200270140
    CharacterId: 20027
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200270120
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 다시 생각해 보니, 나도 좋은 것 같아.
    MessageJP: 私も……嬉しい
    MessageCN: 我也……很高兴
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270110
    Id: 200270150
    CharacterId: 20027
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200270120
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 다행이야.
    MessageJP: ありがとう
    MessageCN: 谢谢
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270120
    Id: 200270160
    CharacterId: 20027
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200270130
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생님
    MessageJP: 先生
    MessageCN: 老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270130
    Id: 200270170
    CharacterId: 20027
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 200270120
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200270140
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 또……이긴 하지만,
    MessageJP: また今日も……
    MessageCN: 我今天也想……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270140
    Id: 200270180
    CharacterId: 20027
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200270150
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 혹시 지금 괜찮아?
    MessageJP: 大丈夫？
    MessageCN: 可以吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270140
    Id: 200270190
    CharacterId: 20027
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200270150
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 즐거워 보이네, 시로코.
    MessageJP: もちろん、いつでも行くよ
    MessageCN: 当然哦，随时都可以
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270150
    Id: 200270200
    CharacterId: 20027
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200270160
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 몇 번이라도 괜찮으니 신경 쓰지 마.
    MessageJP: なんだか楽しそうだね
    MessageCN: 看起来白子乐在其中呢
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270150
    Id: 200270210
    CharacterId: 20027
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200270160
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아
    MessageJP: ん……
    MessageCN: 唔……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270160
    Id: 200270220
    CharacterId: 20027
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200270170
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 음
    MessageJP: うん
    MessageCN: 嗯
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270160
    Id: 200270230
    CharacterId: 20027
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200270170
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 응
    MessageJP: そうかも
    MessageCN: 可能是吧
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270170
    Id: 200270240
    CharacterId: 20027
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200273
    NextGroupId: 200270180
    FeedbackTimeMillisec: 2000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생님
    MessageJP: 先生
    MessageCN: 老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270180
    Id: 200270250
    CharacterId: 20027
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 200270170
    PreConditionFavorScheduleId: 200273
    FavorScheduleId: 0
    NextGroupId: 200270190
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 자?
    MessageJP: 起きてる？
    MessageCN: 还醒着吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270190
    Id: 200270260
    CharacterId: 20027
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200270200
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 자는 건가
    MessageJP: もう寝ちゃったかな
    MessageCN: 睡着了吗
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270190
    Id: 200270270
    CharacterId: 20027
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200270200
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 이 이른 새벽에 모모톡이?
    MessageJP: こんな時間にどうしたの？
    MessageCN: 这么晚了，白子是有什么事吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270200
    Id: 200270280
    CharacterId: 20027
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200270210
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 시로코는? 설마 밤을 새운 거야?
    MessageJP: シロコ……？
    MessageCN: 白子……？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270200
    Id: 200270290
    CharacterId: 20027
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200270210
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아
    MessageJP: あ……
    MessageCN: 啊……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270210
    Id: 200270300
    CharacterId: 20027
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 0
    FeedbackTimeMillisec: 2000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 응 조금
    MessageJP: うん
    MessageCN: 嗯
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270210
    Id: 200270310
    CharacterId: 20027
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 0
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 잠이 안 와서
    MessageJP: ちょっと、眠れなくて
    MessageCN: 有点，睡不着
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200270210
    Id: 200270320
    CharacterId: 20027
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200275
    NextGroupId: 0
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
