CharacterId: 20035
translator: 今天早睡了吗
title:
  - TextKr: 또 다른 수행(?)
    TextJp: また別の修行（？）
    TextCn: 另一种（?）修行
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 2003502
    FavorScheduleId: 200352
    CharacterId: 20035
    unsure: false
  - TextKr: 속성 강좌
    TextJp: 速成講座
    TextCn: 速成班
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 2003503
    FavorScheduleId: 200353
    CharacterId: 20035
    unsure: false
  - TextKr: 좋은 잠, 좋은 꿈.
    TextJp: 良い眠り、良い夢
    TextCn: 好睡眠，好梦境
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 2003505
    FavorScheduleId: 200355
    CharacterId: 20035
    unsure: false
content:
  - MessageKR: 안녕, 선생님.
    MessageJP: おはよう、先生
    MessageCN: 早上好，老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350010
    Id: 200350010
    CharacterId: 20035
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 오. 츠바키네.
    MessageJP: お、ツバキ
    MessageCN: 噢，椿啊
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350020
    Id: 200350020
    CharacterId: 20035
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350030
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 오늘도 수행 중이야?
    MessageJP: 今日も修行中？
    MessageCN: 今天也在修行吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350020
    Id: 200350030
    CharacterId: 20035
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350030
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 맞아.
    MessageJP: そうだよ
    MessageCN: 没错
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350030
    Id: 200350040
    CharacterId: 20035
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350040
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 이번엔 특별히
    MessageJP: 今回は特別に
    MessageCN: 这次比较特别
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350040
    Id: 200350050
    CharacterId: 20035
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350050
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 수행을 위해…… 더욱 심기일전해서
    MessageJP: 修行のために……もっと心機一転して
    MessageCN: 为了修行……我要再改变一下想法
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350050
    Id: 200350060
    CharacterId: 20035
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350060
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 옷까지 바꿔 입었으니까.
    MessageJP: 服まで着替えたから
    MessageCN: 还换了衣服呢
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350050
    Id: 200350070
    CharacterId: 20035
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350060
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 옷을 바꿔 입었다고?
    MessageJP: 服を着替えたの？
    MessageCN: 椿把身上的衣服换掉了吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350060
    Id: 200350080
    CharacterId: 20035
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350070
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 응.
    MessageJP: うん
    MessageCN: 嗯
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350070
    Id: 200350090
    CharacterId: 20035
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350080
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 백귀야행에 오게 되면
    MessageJP: 百鬼夜行に来れば
    MessageCN: 老师来百鬼夜行的话
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350080
    Id: 200350100
    CharacterId: 20035
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350090
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 보여 줄게?
    MessageJP: 見せてあげるね
    MessageCN: 我给老师看看吧
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350080
    Id: 200350110
    CharacterId: 20035
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200352
    NextGroupId: 200350090
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 있잖아. 선생님.
    MessageJP: ねえ、先生
    MessageCN: 那个，老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350090
    Id: 200350120
    CharacterId: 20035
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 200350080
    PreConditionFavorScheduleId: 200352
    FavorScheduleId: 0
    NextGroupId: 200350100
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 지금부터 샬레로 갈 생각인데, 괜찮지?
    MessageJP: 今からシャーレに行くけど、いい？
    MessageCN: 我现在，能去夏莱吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350100
    Id: 200350130
    CharacterId: 20035
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350110
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 물론 괜찮지만.
    MessageJP: もちろん、いいけど
    MessageCN: 当然可以
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350110
    Id: 200350140
    CharacterId: 20035
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350120
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 츠바키가 여기까지 찾아오다니, 드문 일이네.
    MessageJP: ツバキがわざわざ来るだなんて、珍しいね
    MessageCN: 椿要特意来夏莱，还真是少见呢
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350110
    Id: 200350150
    CharacterId: 20035
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350120
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 당연한 거야.
    MessageJP: 当然だよ
    MessageCN: 当然啦
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350120
    Id: 200350160
    CharacterId: 20035
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350130
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 지금의 나는, 수면 가이드 카스가 츠바키니까.
    MessageJP: 今の私は、睡眠ガイドの春日ツバキだから
    MessageCN: 因为我今天，是睡眠向导春日椿嘛
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350120
    Id: 200350170
    CharacterId: 20035
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350130
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 예전에 선생님에게 수면 가이드를 제대로 해 주지 못했으니까…….
    MessageJP: この前は先生に睡眠のガイドをちゃんとしてあげられなかったし……
    MessageCN: 之前都没能好好给老师做睡眠引导……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350130
    Id: 200350180
    CharacterId: 20035
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350140
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 오늘은 그 분량만큼 철저하게 가이드를 해 줄게.
    MessageJP: 今日はその分、徹底的にガイドしてあげるね
    MessageCN: 今天我就来给老师彻底引导一遍哦
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350130
    Id: 200350190
    CharacterId: 20035
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350140
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 결국 샬레에서 자겠다는 소리구나…….
    MessageJP: 結局シャーレで寝るってことなんだね……
    MessageCN: 结果就是在夏莱睡觉对吧……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350140
    Id: 200350200
    CharacterId: 20035
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350150
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 그건 완전한 진실이 아니야.
    MessageJP: そうかな
    MessageCN: 可能是吧
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350150
    Id: 200350210
    CharacterId: 20035
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350160
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 왜냐하면 선생님도 같이 자야 하니까.
    MessageJP: でも、先生も一緒に寝るんだよ
    MessageCN: 不过，老师也会一起睡哦
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350150
    Id: 200350220
    CharacterId: 20035
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200353
    NextGroupId: 200350160
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 선생님.
    MessageJP: 先生
    MessageCN: 老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350160
    Id: 200350230
    CharacterId: 20035
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 200350150
    PreConditionFavorScheduleId: 200353
    FavorScheduleId: 0
    NextGroupId: 200350170
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 업무 차 백귀야행에 온다고 들었는데, 맞아?
    MessageJP: 仕事のことで百鬼夜行に来るって聞いたけど、本当？
    MessageCN: 听说您要来百鬼夜行办事，是真的吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350170
    Id: 200350240
    CharacterId: 20035
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350180
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 응. 그렇게 됐어.
    MessageJP: うん。そうだよ
    MessageCN: 嗯。是真的哦
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350180
    Id: 200350250
    CharacterId: 20035
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350190
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 그렇구나.
    MessageJP: そっか
    MessageCN: 这样啊
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350190
    Id: 200350260
    CharacterId: 20035
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350200
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 헤헤.
    MessageJP: ふふ
    MessageCN: 呼呼
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350190
    Id: 200350270
    CharacterId: 20035
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350200
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 그러면 말이지.
    MessageJP: それじゃ
    MessageCN: 这样的话
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350200
    Id: 200350280
    CharacterId: 20035
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350210
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 업무가 끝나면…… 연락 줄래?
    MessageJP: 仕事が終わったら……連絡してくれる？
    MessageCN: 老师办完事之后……能联系一下我吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350200
    Id: 200350290
    CharacterId: 20035
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350210
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 그래. 그렇게 할게.
    MessageJP: うん、分かった
    MessageCN: 嗯，我知道了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350210
    Id: 200350300
    CharacterId: 20035
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350220
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 예전에도 못했던 수면 가이드.
    MessageJP: この前もできなかった睡眠ガイド
    MessageCN: 这次我一定要
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350220
    Id: 200350310
    CharacterId: 20035
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350230
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 이번에는 확실하게 해 줄 테니까.
    MessageJP: 今回は確実にしてあげるから
    MessageCN: 把之前没做完的睡眠指引给老师补上
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350220
    Id: 200350320
    CharacterId: 20035
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200350230
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 은근히 마음에 두고 있었구나……
    MessageJP: 結構気にしていたんだね……
    MessageCN: 椿这么在意这件事啊……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200350230
    Id: 200350330
    CharacterId: 20035
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200355
    NextGroupId: 0
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
