CharacterId: 20034
translator: 今天早睡了吗
title:
  - TextJp: 目的のために
    TextCn: 为了达成目的
    TextKr: 목적을 달성하는 방법
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 2003402
    FavorScheduleId: 200342
    CharacterId: 20034
    unsure: false
  - TextJp: 希望をかなえるために
    TextCn: 为了实现愿望
    TextKr: Do It Yourself!
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 2003403
    FavorScheduleId: 200343
    CharacterId: 20034
    unsure: false
  - TextJp: 幸運を迎えるために
    TextCn: 为了迎接幸运
    TextKr: 행운을 이루기 위해
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 2003405
    FavorScheduleId: 200345
    CharacterId: 20034
    unsure: false
content:
  - MessageKR: 해마다 이 시즌이 되면, 상점가에서 여러 가지 이벤트를 개최하곤 하죠.
    MessageJP: 今のシーズン、商店街では色々なイベントが開かれていますよね
    MessageCN: 商店街在这个季节会举办各种各样的活动呢
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340010
    Id: 200340010
    CharacterId: 20034
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200340020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 아카리도 그런 이벤트에 흥미가 있구나.
    MessageJP: アカリもそういうのに興味あるんだね
    MessageCN: 明里对这种也很感兴趣呢
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340020
    Id: 200340020
    CharacterId: 20034
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200340030
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 물론이죠.
    MessageJP: 当たり前ですよ★
    MessageCN: 这是当然★
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340030
    Id: 200340030
    CharacterId: 20034
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200340040
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 그것이 먹는 것과 관련된 일이라면, 특히요.
    MessageJP: こういうのって往々にして新たな美食に出会えるチャンスですから
    MessageCN: 毕竟这往往是一个邂逅全新美食的机会呢
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340030
    Id: 200340040
    CharacterId: 20034
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200340040
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 상점가…… 이벤트…… 먹는 것……?
    MessageJP: 美食に……？
    MessageCN: 邂逅……美食……？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340040
    Id: 200340050
    CharacterId: 20034
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200340050
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 후후.
    MessageJP: フフ
    MessageCN: 呵呵
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340050
    Id: 200340060
    CharacterId: 20034
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200340060
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 기대되시나요?
    MessageJP: 先生、そう考えたらワクワクしませんか？
    MessageCN: 这么一想是不是就很兴奋呢，老师？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340050
    Id: 200340070
    CharacterId: 20034
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200340060
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 저는 기대되네요!
    MessageJP: 私はとってもワクワクしています！
    MessageCN: 我可是非常兴奋！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340050
    Id: 200340080
    CharacterId: 20034
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200342
    NextGroupId: 200340060
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 오조니는 맛있는 음식이죠.
    MessageJP: お雑煮って美味しいですよね
    MessageCN: 年糕汤很美味对吧
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340060
    Id: 200340090
    CharacterId: 20034
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 200340050
    PreConditionFavorScheduleId: 200342
    FavorScheduleId: 0
    NextGroupId: 200340070
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 그 덕분에 사소한 문제가 생겨 버렸지만요.
    MessageJP: それ故に、些細な問題があるともいえます
    MessageCN: 但正因如此，也会有一些琐碎的问题
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340070
    Id: 200340100
    CharacterId: 20034
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200340080
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 아카리가 사소하다고 말하니까…….
    MessageJP: アカリが言うと
    MessageCN: 这话由明里说出来
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340080
    Id: 200340110
    CharacterId: 20034
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200340090
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 왠지 그렇게 들리지가 않아…….
    MessageJP: ちっとも些細じゃなさそう……
    MessageCN: 就感觉一点也不琐碎啊……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340080
    Id: 200340120
    CharacterId: 20034
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200340090
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: "어머나. "
    MessageJP: あら
    MessageCN: 哎呀
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340090
    Id: 200340130
    CharacterId: 20034
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200340100
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 이번엔 정말로 사소한 일이에요.
    MessageJP: 今回は本当に些細ですよ？
    MessageCN: 这次可真的是很琐碎的事情哦？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340090
    Id: 200340140
    CharacterId: 20034
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200340100
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: "오조니용으로 떡을 너무 많이 넣는 바람에, "
    MessageJP: 美味しさのあまり家のお餅を全部
    MessageCN: 因为太好吃了，所以我把家里所有的年糕
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340100
    Id: 200340150
    CharacterId: 20034
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200340110
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 집에 있는 떡을 전부 사용해 버렸다는 문제거든요.
    MessageJP: お雑煮用に使い切ってしまったんです
    MessageCN: 都拿去煮年糕汤了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340100
    Id: 200340160
    CharacterId: 20034
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200340110
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 적당함이야말로 미덕인 것이었을텐데…….
    MessageJP: 過ぎたるは猶及ばざるが如し……
    MessageCN: 过犹不及啊……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340110
    Id: 200340170
    CharacterId: 20034
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200340120
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 하지만 저는 떡을 더 많이 먹고 싶은걸요.
    MessageJP: だって、お餅をたくさん食べたかったんですもの
    MessageCN: 因为，我想吃很多很多年糕嘛
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340120
    Id: 200340180
    CharacterId: 20034
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200340130
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 바로 그래서.
    MessageJP: それで
    MessageCN: 于是呢
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340130
    Id: 200340190
    CharacterId: 20034
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200340140
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 제가 준비한 것이 있답니다.
    MessageJP: 解決策を思いついたんです
    MessageCN: 我就想到了一个解决办法
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340130
    Id: 200340200
    CharacterId: 20034
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200343
    NextGroupId: 200340140
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 이런 시즌에는
    MessageJP: 特別な食べ物と一緒に、特別な時間を過ごす……
    MessageCN: 和特别的食物一起，度过特别的时光……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340140
    Id: 200340210
    CharacterId: 20034
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 200340130
    PreConditionFavorScheduleId: 200343
    FavorScheduleId: 0
    NextGroupId: 200340150
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 특별한 음식을 먹으면서, 특별한 시간을 기리곤 하죠.
    MessageJP: このシーズンの
    MessageCN: 这就是这个季节
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340150
    Id: 200340220
    CharacterId: 20034
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200340160
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 멋진 문화라고 생각해요.
    MessageJP: 最も素敵なところです
    MessageCN: 最美妙的地方
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340150
    Id: 200340230
    CharacterId: 20034
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200340160
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 특별히 먹고 싶은 거라도 있어?
    MessageJP: 何か食べたいものでもある？
    MessageCN: 明里有什么想吃的东西吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340160
    Id: 200340240
    CharacterId: 20034
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200340170
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 먹고 싶은 것이라기보단.
    MessageJP: 食べたいものというより
    MessageCN: 与其说是有想吃的东西
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340170
    Id: 200340250
    CharacterId: 20034
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200340180
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 갑자기, 먹어 보고 싶어진 것이 있어요.
    MessageJP: 食べてみたくなったもの、があります
    MessageCN: 不如说是，有想吃吃看的的东西
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340170
    Id: 200340260
    CharacterId: 20034
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200340180
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 그런 의미에서 소문이라는 것은 강력하죠.
    MessageJP: 口コミの威力ってすごいですね
    MessageCN: 口碑的威力还真是不容小觑呢
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340180
    Id: 200340270
    CharacterId: 20034
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200340190
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 없던 마음도 생겨나게 하거든요.
    MessageJP: 自然と食べたい気持ちにさせられちゃいます
    MessageCN: 自然而然地就让人想吃了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340180
    Id: 200340280
    CharacterId: 20034
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200340190
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 어딘가에서 맛있는 음식에 대한 소식을 들은 모양이네.
    MessageJP: グルメの記事でも読んだのかな？
    MessageCN: 明里是看了什么美食报道吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340190
    Id: 200340290
    CharacterId: 20034
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200340200
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 정확합니다.
    MessageJP: その通り
    MessageCN: 没错
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340200
    Id: 200340300
    CharacterId: 20034
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 0
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 선생님께서도 들어 보시면 흥미가 생기실 걸요?
    MessageJP: きっと先生も、気になると思いますよ！
    MessageCN: 我觉得，老师肯定也会很感兴趣的！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200340200
    Id: 200340310
    CharacterId: 20034
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200345
    NextGroupId: 0
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
