CharacterId: 26014
translator: 今天早睡了吗
title:
  - TextJp: 休むなら心のタガを外して
    TextCn: 休息就要尽情放松
    TextKr: 일일외식록 카린
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 2601402
    FavorScheduleId: 260142
    CharacterId: 26014
    unsure: false
  - TextJp: 休むなら二人一緒に
    TextCn: 休息就要两人一起
    TextKr: 더욱 격렬히 아무것도 안 하기
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 2601403
    FavorScheduleId: 260143
    CharacterId: 26014
    unsure: false
  - TextJp: 休むなら特別な休日を
    TextCn: 休息就要特别的假日
    TextKr: 등굣길의 추억
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 2601405
    FavorScheduleId: 260145
    CharacterId: 26014
    unsure: false
content:
  - MessageKR: 임무가 끝났다
    MessageJP: 先生、お疲れ様
    MessageCN: 老师，辛苦了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140010
    Id: 260140010
    CharacterId: 26014
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 앞으로 며칠 동안은 휴일이지만
    MessageJP: 任務が一段落したから
    MessageCN: 我任务告一段落了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140020
    Id: 260140020
    CharacterId: 26014
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140030
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 교복을 입고 지낼 것 같다
    MessageJP: 今日から数日、お休みになったんだ
    MessageCN: 所以从今天开始，我能放几天假
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140020
    Id: 260140030
    CharacterId: 26014
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140030
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 휴일이라니 잘됐네
    MessageJP: お休み、いいなぁ……
    MessageCN: 放假，真好啊……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140030
    Id: 260140040
    CharacterId: 26014
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140040
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 쉬는 날엔 보통 뭘 해?
    MessageJP: 普段、休日は何をするの？
    MessageCN: 花凛放假一般做什么？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140040
    Id: 260140050
    CharacterId: 26014
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140050
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 음
    MessageJP: うーん
    MessageCN: 唔
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140050
    Id: 260140060
    CharacterId: 26014
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140060
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 뭘 하지?
    MessageJP: いつもは……任務の時と変わらないな
    MessageCN: 就和……有任务的时候差不多吧
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140050
    Id: 260140070
    CharacterId: 26014
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140060
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: ……저한테 물어보셔도?
    MessageJP: ……ちょっとそっちに行ってもいい？
    MessageCN: ……我能去你那边吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140060
    Id: 260140080
    CharacterId: 26014
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 260142
    NextGroupId: 260140070
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 선생님
    MessageJP: 先生、起きてるか？
    MessageCN: 老师，起来了吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140070
    Id: 260140090
    CharacterId: 26014
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 260140060
    PreConditionFavorScheduleId: 260142
    FavorScheduleId: 0
    NextGroupId: 260140080
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 이른 시간에 연락했네?
    MessageJP: こんな時間にどうしたの？
    MessageCN: 这个点找我，有什么事吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140080
    Id: 260140100
    CharacterId: 26014
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140090
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 음
    MessageJP: えっと
    MessageCN: 那个
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140090
    Id: 260140110
    CharacterId: 26014
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140100
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 미안해
    MessageJP: すまない
    MessageCN: 不好意思
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140090
    Id: 260140120
    CharacterId: 26014
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140100
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 그게
    MessageJP: 実は……休日であることを忘れて
    MessageCN: 其实……我忘了今天放假
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140100
    Id: 260140130
    CharacterId: 26014
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140110
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 휴일인 걸 깜빡하고 일찍 일어났거든
    MessageJP: いつもの時間に起きてしまったんだ
    MessageCN: 就按往常一样的时间起床了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140100
    Id: 260140140
    CharacterId: 26014
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140110
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 평일에 익숙해지면 종종 그렇지…….
    MessageJP: 規則的な生活をしてると、そうなるよね……
    MessageCN: 一直过规律生活就会这样呢……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140110
    Id: 260140150
    CharacterId: 26014
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140120
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 그래서 그냥 멍한 상태
    MessageJP: 正直、時間を持て余してしまってて……
    MessageCN: 我现在，说实话还剩不少时间……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140120
    Id: 260140160
    CharacterId: 26014
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140130
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 다음은 뭘 해야 할지 막막해서…….
    MessageJP: 先生さえよければ、シャーレに行ってもいいか？
    MessageCN: 要是老师方便的话，我能去夏莱吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140120
    Id: 260140170
    CharacterId: 26014
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140130
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 그럼 샬레에 와서 쉬는 건 어때?
    MessageJP: いいよ。待ってるね
    MessageCN: 好啊。我等你
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140130
    Id: 260140180
    CharacterId: 26014
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 260143
    NextGroupId: 260140140
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 오늘은 즐거웠다
    MessageJP: 今日は楽しかった
    MessageCN: 今天很开心
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140140
    Id: 260140190
    CharacterId: 26014
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 260140130
    PreConditionFavorScheduleId: 260143
    FavorScheduleId: 0
    NextGroupId: 260140150
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 그리고
    MessageJP: それから
    MessageCN: 还有
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140150
    Id: 260140200
    CharacterId: 26014
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140160
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 아까는 미안했다
    MessageJP: 分かってはいたが先生はいつも忙しいのだな
    MessageCN: 虽然我也知道，但是老师一直都很忙啊
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140150
    Id: 260140210
    CharacterId: 26014
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140160
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 선생님에게 내 도움이 필요치 않다고 생각하니
    MessageJP: 私には「休め」と言うのに……
    MessageCN: 就这样还让我去“休息”……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140160
    Id: 260140220
    CharacterId: 26014
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140170
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 조금 조급해져서
    MessageJP: 先生こそちゃんと休めているのか？
    MessageCN: 老师才是，有好好休息吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140160
    Id: 260140230
    CharacterId: 26014
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140170
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 카린의 휴일을 방해하고 싶지 않았어
    MessageJP: カリンのおかげで今日は久々にゆっくりできたよ
    MessageCN: 多亏了花凛，今天难得好好休息一次哦
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140170
    Id: 260140240
    CharacterId: 26014
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140180
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 부담 갖지 않아도 된다
    MessageJP: 私が必要な時は、遠慮なく頼って欲しい
    MessageCN: 如果有必须依赖我的时候，希望老师不要顾虑
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140180
    Id: 260140250
    CharacterId: 26014
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140190
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 선생님을 돕는 거라면 언제든 환영이니까
    MessageJP: 先生の手伝いなら、いつでも歓迎だ
    MessageCN: 如果是给老师帮忙，我一直很欢迎
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140180
    Id: 260140260
    CharacterId: 26014
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140190
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 선생님
    MessageJP: 先生
    MessageCN: 老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140190
    Id: 260140270
    CharacterId: 26014
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 260140180
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140200
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 희소식이다
    MessageJP: 私なりの休日の過ごし方を思いついたんだ
    MessageCN: 我想到自己的休假方式了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140200
    Id: 260140280
    CharacterId: 26014
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140210
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 희소식?
    MessageJP: やったね！
    MessageCN: 做到了呢！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140210
    Id: 260140290
    CharacterId: 26014
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140220
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 아이디어가 떠올랐다
    MessageJP: それで…もしよかったら……
    MessageCN: 然后……要是方便的话……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140220
    Id: 260140300
    CharacterId: 26014
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140230
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 특별한 휴일을 보낼 아이디어가
    MessageJP: 先生にも一緒に来てもらいたいんだけど……
    MessageCN: 我希望老师也和我一起来……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140220
    Id: 260140310
    CharacterId: 26014
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140230
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 뭔지는 몰라도, 내가 힘껏 도와 줄게!
    MessageJP: 喜んで行かせてもらうよ
    MessageCN: 很乐意奉陪哦
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140230
    Id: 260140320
    CharacterId: 26014
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140240
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 고마워
    MessageJP: ありがとう
    MessageCN: 谢谢
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140240
    Id: 260140330
    CharacterId: 26014
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140250
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 선생님의 도움은 언제나 환영이니까
    MessageJP: 先生が一緒なら、きっと楽しい
    MessageCN: 要是和老师一起，一定很有意思
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140240
    Id: 260140340
    CharacterId: 26014
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140250
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 지금부터 등교할 생각이라서
    MessageJP: じゃあ、これから登校するから
    MessageCN: 那么，我就去上学了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140250
    Id: 260140350
    CharacterId: 26014
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140260
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 함께할 생각이 있다면, 우리 집 앞으로 와주면 좋겠다
    MessageJP: 迎えに来てもらえるか？
    MessageCN: 老师来接我吧？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140250
    Id: 260140360
    CharacterId: 26014
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260140260
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: ……등교?
    MessageJP: ……え？
    MessageCN: ……诶？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260140260
    Id: 260140370
    CharacterId: 26014
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 260145
    NextGroupId: 260140270
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
