/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AssetPreviewer: typeof import('./components/ResourceExplorer/AssetPreviewer.vue')['default']
    EditorLayout: typeof import('./components/EditorLayout/index.vue')['default']
    FileItem: typeof import('./components/ResourceExplorer/FileItem.vue')['default']
    README: typeof import('./components/README.md')['default']
    ResourceExplorer: typeof import('./components/ResourceExplorer/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TButton: typeof import('tdesign-vue-next')['Button']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
