/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    CardContainer: typeof import("./components/Card/CardContainer.vue")["default"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCol: typeof import("element-plus/es")["ElCol"];
    ElConfigProvider: typeof import("element-plus/es")["ElConfigProvider"];
    ElDialog: typeof import("element-plus/es")["ElDialog"];
    ElResult: typeof import("element-plus/es")["ElResult"];
    ElRow: typeof import("element-plus/es")["ElRow"];
    ElScrollbar: typeof import("element-plus/es")["ElScrollbar"];
    EnProcess: typeof import("./components/EnProcess.md")["default"];
    MainAsideMenu: typeof import("./components/MainAsideMenu.vue")["default"];
    MainBanner: typeof import("./components/MainBanner.vue")["default"];
    PageHeader: typeof import("./components/PageHeader.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    ShadowCard: typeof import("./components/ShadowCard.vue")["default"];
    SubPageIndex: typeof import("./components/SubPageIndex.vue")["default"];
    TheFooter: typeof import("./components/TheFooter.vue")["default"];
    ZhProcess: typeof import("./components/ZhProcess.md")["default"];
  }
}
