- filename: ClanChat_Emoji_01_Jp
  alias:
    - こんにちは
    - 你好
    - 早上好
    - arona
    - アロナ
    - あろな
    - 阿罗娜
    - 彩奈
- filename: ClanChat_Emoji_02_Jp
  alias:
    - 青輝石
    - あおきせき
    - 青辉石
    - 宝石
    - 石头
    - arona
    - アロナ
    - あろな
    - 阿罗娜
    - 彩奈
- filename: ClanChat_Emoji_03_Jp
  alias:
    - 頑張ってください
    - 加油
    - hifumi
    - ヒフミ
    - ひふみ
    - 日富美
- filename: ClanChat_Emoji_04_Jp
  alias:
    - ありがとうございます
    - 谢谢
    - airi
    - アイリ
    - あいり
    - 爱莉
- filename: ClanChat_Emoji_05_Jp
  alias:
    - ぎゃああああ
    - 嘎啊啊啊啊
    - tsurugi
    - ツルギ
    - つるぎ
    - 鹤城
- filename: ClanChat_Emoji_06_Jp
  alias:
    - 大丈夫ですか
    - 还好吗
    - 没事吧
    - 没事吗
    - serina
    - セリナ
    - せりな
    - 芹那
- filename: ClanChat_Emoji_07_Jp
  alias:
    - ごめんなさい
    - 对不起
    - haruka
    - ハルカ
    - はるか
    - 遥香
- filename: ClanChat_Emoji_08_Jp
  alias:
    - ふ〜ん
    - 嗯
    - mutsuki
    - ムツキ
    - むつき
    - 睦月
- filename: ClanChat_Emoji_09_Jp
  alias:
    - '?'
    - ？
    - aru
    - アル
    - ある
    - 阿露
- filename: ClanChat_Emoji_10_Jp
  alias:
    - 行こう
    - 走吧
    - 出发吧
    - hina
    - ヒナ
    - ひな
    - 日奈
- filename: ClanChat_Emoji_11_Jp
  alias:
    - ダメです
    - だめです
    - 駄目です
    - yuuka
    - ユウカ
    - ゆうか
    - 优香
- filename: ClanChat_Emoji_12_Jp
  alias:
    - midori
    - みどり
    - ミドリ
    - 緑
    - 绿
- filename: ClanChat_Emoji_13_Jp
  alias:
    - うわ〜ん
    - 呜哇
    - momoi
    - モモイ
    - ももい
    - 桃井
- filename: ClanChat_Emoji_14_Jp
  alias:
    - 神ゲーです
    - 神游戏
    - arisu
    - アリス
    - ありす
    - 爱丽丝
- filename: ClanChat_Emoji_15_Jp
  alias:
    - ガタガタ
    - yuzu
    - ユズ
    - ゆず
    - 柚子
- filename: ClanChat_Emoji_16_Jp
  alias:
    - いい子いい子
    - いいこいいこ
    - 好孩子好孩子
    - 乖孩子乖孩子
    - shun
    - シュン
    - しゅん
    - 瞬
- filename: ClanChat_Emoji_17_Jp
  alias:
    - chise
    - チセ
    - ちせ
    - 千世
- filename: ClanChat_Emoji_18_Jp
  alias:
    - OK
    - shiroko
    - シロコ
    - しろこ
    - 白子
- filename: ClanChat_Emoji_19_Jp
  alias:
    - おやすみ
    - 晚安
    - hoshino
    - ホシノ
    - ほしの
    - 星野
- filename: ClanChat_Emoji_20_Jp
  alias:
    - どやぁ
    - cherino
    - チェリノ
    - ちぇりの
    - 切里诺
- filename: ClanChat_Emoji_21_Jp
  alias:
    - なななっ何ですって
    - なななっなんですって
    - 何ですって
    - 什什什什么
    - aru
    - アル
    - ある
    - 阿露
- filename: ClanChat_Emoji_22_Jp
  alias:
    - もっと褒めてもいいのよ
    - 可以多夸夸我
    - 请多夸夸我
    - aru
    - アル
    - ある
    - 阿露
- filename: ClanChat_Emoji_23_Jp
  alias:
    - 私も頑張るわ
    - 我也会加油的
    - aru
    - アル
    - ある
    - 阿露
- filename: ClanChat_Emoji_24_Jp
  alias:
    - すっすみません
    - すみません
    - 对不起
    - haruka
    - ハルカ
    - はるか
    - 遥香
- filename: ClanChat_Emoji_25_Jp
  alias:
    - '…'
    - '...'
    - '……'
    - kayoko
    - カヨコ
    - かよこ
    - 佳代子
- filename: ClanChat_Emoji_26_Jp
  alias:
    - あははっうける
    - mutsuki
    - ムツキ
    - むつき
    - 睦月
- filename: ClanChat_Emoji_27_Jp
  alias:
    - '!?'
    - '！？'
    - hina
    - ヒナ
    - ひな
    - 日奈
- filename: ClanChat_Emoji_28_Jp
  alias:
    - わかった
    - 知道了
    - 了解
    - 明白
    - shiroko
    - シロコ
    - しろこ
    - 白子
- filename: ClanChat_Emoji_29_Jp
  alias:
    - すごく楽しかった
    - 很开心
    - shiroko
    - シロコ
    - しろこ
    - 白子
- filename: ClanChat_Emoji_30_Jp
  alias:
    - 最近の若いやつにはついていけん
    - 最近的年轻人真是跟不上
    - hoshino
    - ホシノ
    - ほしの
    - 星野
- filename: ClanChat_Emoji_31_Jp
  alias:
    - 許さない
    - 不能原谅
    - serika
    - セリカ
    - せりか
    - 芹香
- filename: ClanChat_Emoji_32_Jp
  alias:
    - アディオース
    - あでぃおーす
    - adios
    - nonomi
    - ノノミ
    - ののみ
    - 野宫
- filename: ClanChat_Emoji_33_Jp
  alias:
    - お疲れ様です
    - 辛苦了
    - ayane
    - アヤネ
    - あやね
    - 绫音
- filename: ClanChat_Emoji_34_Jp
  alias:
    - tsurugi
    - ツルギ
    - つるぎ
    - 鹤城
- filename: ClanChat_Emoji_35_Jp
  alias:
    - ひゃひゃひゃひゃ
    - tsurugi
    - ツルギ
    - つるぎ
    - 鹤城
- filename: ClanChat_Emoji_36_Jp
  alias:
    - しあわせ
    - hasumi
    - ハスミ
    - はすみ
    - 莲见
- filename: ClanChat_Emoji_37_Jp
  alias:
    - 私に何かできることはありますか
    - 有什么我能帮忙的吗
    - hifumi
    - ヒフミ
    - ひふみ
    - 日富美
- filename: ClanChat_Emoji_38_Jp
  alias:
    - ポカーン
    - mashiro
    - マシロ
    - ましろ
    - 真白
- filename: ClanChat_Emoji_39_Jp
  alias:
    - ええええええ
    - 诶诶诶诶诶诶
    - izuna
    - イズナ
    - いずな
    - 泉奈
- filename: ClanChat_Emoji_40_Jp
  alias:
    - この変態
    - 你这个变态
    - iori
    - イオリ
    - いおり
    - 伊织
- filename: ClanChat_Emoji_41_Jp
  alias:
    - zzz
    - tsubaki
    - ツバキ
    - つばき
    - 椿
- filename: ClanChat_Emoji_42_Jp
  alias:
    - お仕事の時間です
    - 工作时间到了
    - arona
    - アロナ
    - あろな
    - 阿罗娜
    - 彩奈
- filename: ClanChat_Emoji_43_Jp
  alias:
    - 暇だなあ
    - 好闲
    - sora
    - ソラ
    - そら
    - 空
- filename: ClanChat_Emoji_44_Jp
  alias:
    - あ定時だ
- filename: ClanChat_Emoji_45_Jp
  alias:
    - 全て因数分解してやるわ
    - 全部给你因数分解
    - yuuka
    - ユウカ
    - ゆうか
    - 优香
- filename: ClanChat_Emoji_46_Jp
  alias:
    - 先生は家に帰らないの
    - 老师不回家吗
    - chise
    - チセ
    - ちせ
    - 千世
- filename: ClanChat_Emoji_47_Jp
  alias:
    - クックックッ
    - 库库库
    - kurofuku
    - 黒服
    - 黑服
- filename: ClanChat_Emoji_48_Jp
  alias:
    - 自分で作ったら
    - 自己做呢
    - fuuka
    - フウカ
    - ふうか
    - 枫香
- filename: ClanChat_Emoji_49_Jp
  alias:
    - 今日もよろしくお願いします
    - 今天也请多多关照
    - arona
    - アロナ
    - あろな
    - 阿罗娜
    - 彩奈
- filename: ClanChat_Emoji_50_Jp
  alias:
    - 一日一悪
    - 一日一恶
    - aru
    - アル
    - ある
    - 阿露
- filename: ClanChat_Emoji_51_Jp
  alias:
    - ん
    - 嗯
    - rin
    - リン
    - りん
    - 凛
- filename: ClanChat_Emoji_52_Jp
  alias:
    - はあ
    - 哈
    - neru
    - ネル
    - ねる
    - 尼禄
- filename: ClanChat_Emoji_53_Jp
  alias:
    - complete
    - 完成
- filename: ClanChat_Emoji_54_Jp
  alias:
    - ふーん
    - 哼
    - momoka
    - モモカ
    - ももか
    - 桃香
- filename: ClanChat_Emoji_55_Jp
  alias:
    - レベルアップしました
    - 升级了
    - 等级提升了
    - aris
    - アリス
    - ありす
    - 爱丽丝
- filename: ClanChat_Emoji_56_Jp
  alias:
    - もう終わりだあああ
    - 已经结束了啊啊啊
    - momoi
    - モモイ
    - ももい
    - 桃井
    - midori
    - ミドリ
    - みどり
    - 绿
- filename: ClanChat_Emoji_57_Jp
  alias:
    - ごめんなさい
    - 对不起
    - yuzu
    - ユズ
    - ゆず
    - 柚子
- filename: ClanChat_Emoji_58_Jp
  alias:
    - 任せて
    - 交给我吧
    - asuna
    - アスナ
    - あすな
    - 明日奈
- filename: ClanChat_Emoji_59_Jp
  alias:
    - ありがとうございます
    - 谢谢
    - nonomi
    - ノノミ
    - ののみ
    - 野宫
- filename: ClanChat_Emoji_60_Jp
  alias:
    - 計算通り完璧
    - 计算通
    - yuuka
    - ユウカ
    - ゆうか
- filename: ClanChat_Emoji_61_Jp
  alias:
    - おめでとうございます
    - 恭喜
    - nonomi
    - ノノミ
    - ののみ
    - 野宫
- filename: ClanChat_Emoji_62_Jp
  alias:
    - 嬉しいです
    - 高兴
    - wakamo
    - ワカモ
    - わかも
    - 若藻
- filename: ClanChat_Emoji_63_Jp
  alias:
    - イエーア
    - 呀
    - pina
    - フィーナ
    - ふぃーな
    - 菲娜
- filename: ClanChat_Emoji_64_Jp
  alias:
    - うんうん
    - 嗯嗯
    - asuna
    - アスナ
    - あすな
    - 明日奈
- filename: ClanChat_Emoji_65_Jp
  alias:
    - hasumi
    - ハスミ
    - はすみ
    - 莲见
- filename: ClanChat_Emoji_66_Jp
  alias:
    - '…'
    - '...'
    - '……'
    - koharu
    - コハル
    - こはる
    - 小春
- filename: ClanChat_Emoji_67_Jp
  alias:
    - いただきまーっす
    - 我开动了
    - izumi
    - イズミ
    - いずみ
    - 泉
- filename: ClanChat_Emoji_68_Jp
  alias:
    - nodoka
    - のどか
    - ノドカ
    - 和香
    - 望远镜
    - 偷看
    - 偷窥
- filename: ClanChat_Emoji_69_Jp
  alias:
    - はあはあ
    - 嘶哈嘶哈
    - ako
    - アコ
    - あこ
    - 亚子
- filename: ClanChat_Emoji_70_Jp
  alias:
    - あずさ
    - アズサ
    - azusa
    - 梓
- filename: ClanChat_Emoji_71_Jp
  alias:
    - パチパチパチ
    - tomoe
    - ともえ
    - トモエ
    - 巴
- filename: ClanChat_Emoji_72_Jp
  alias:
    - あかね
    - アカネ
    - akane
- filename: ClanChat_Emoji_73_Jp
  alias:
    - ふうか
    - フウカ
    - ふうか
- filename: ClanChat_Emoji_74_Jp
  alias:
    - ごるあっ
    - ねる
    - ネル
    - neru
- filename: ClanChat_Emoji_75_Jp
  alias:
    - 今ちょっと忙しい
    - せりか
    - セリカ
    - serika
- filename: ClanChat_Emoji_76_Jp
  alias:
    - イズナ
    - いずな
    - izuna
- filename: ClanChat_Emoji_77_Jp
  alias:
    - てへっ
    - ことり
    - コトリ
    - kotori
- filename: ClanChat_Emoji_78_Jp
  alias:
    - おお
    - なつ
    - ナツ
    - natsu
- filename: ClanChat_Emoji_79_Jp
  alias:
    - きりの
    - キリノ
    - kirino
- filename: ClanChat_Emoji_80_Jp
  alias:
    - まり
    - マリ
    - mari
