name: Deploy Website To Production
on:
  push:
    branches:
      - master
      - main

concurrency:
  group: "production-deploy"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0
      - uses: actions/setup-node@main
        with:
          node-version: 22
      - uses: pnpm/action-setup@master
        with:
          version: latest
      - name: Configure npmrc
        run: |
          cp common/config/rush/.npmrc.github common/config/rush/.npmrc
      - name: Verify Change Logs
        run: node common/scripts/install-run-rush.js change --verify
      - name: Rush Update
        run: node common/scripts/install-run-rush.js update
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Generate secret for translator
        env:
          YOUDAO_APP_ID: ${{ secrets.YOUDAO_APP_ID }}
          YOUDAO_APP_SECRET: ${{ secrets.YOUDAO_APP_SECRET }}
          ANTHROPIC_TIER1_SECRET: ${{ secrets.ANTHROPIC_TIER1_SECRET }}
        shell: python
        run: |
          import os
          YOUDAO_APP_ID = os.getenv("YOUDAO_APP_ID")
          YOUDAO_APP_SECRET = os.getenv("YOUDAO_APP_SECRET")
          ANTHROPIC_TIER1_SECRET = os.getenv("ANTHROPIC_TIER1_SECRET")
          with open("./apps/ba-online-toolbox/src/tools/public/secrets.json", "w") as f:
              f.write(f'{{"YOUDAO_APP_ID": "{YOUDAO_APP_ID}", "YOUDAO_APP_SECRET": "{YOUDAO_APP_SECRET}", "ANTHROPIC_TIER1_SECRET": "{ANTHROPIC_TIER1_SECRET}"}}')
      - name: Rush build
        run: node common/scripts/install-run-rush.js build --to blue-archive-story-viewer --verbose
      - name: Viewer rsync deploy
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_PASS_PRODUCTION }}
          ARGS: "-rltgoDzvO -i --delete"
          SOURCE: "./apps/blue-archive-story-viewer/dist/"
          REMOTE_HOST: ${{ secrets.SERVER_HOST_PRODUCTION }}
          REMOTE_USER: ${{ secrets.SERVER_USER_PRODUCTION }}
          TARGET: "/var/www/website"
          EXCLUDE: ".git*"
