name: Issue Checker
on:
  issues:
    types: [opened, edited]
  pull_request_target:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  push:

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: zzyyyl/issue-checker@main
        if: ${{ github.actor != 'renovate[bot]' }}
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/issue-checker.yml
          not-before: 2022-08-05T00:00:00Z
          include-title: 1
